In [5]:
from sklearn.metrics.pairwise import rbf_kernel
import numpy as np

In [6]:
matriz = np.matrix([[1, 2, 3, 4 ],
                    [5, 6, 7, 8 ],
                    [9,10,11,12],
                    [9,10,11,11]])


matriz.nbytes

128

In [17]:
mat = np.matrix([[0,1],
                 [2,3]])
m = mat**2
z = mat * mat

m

matrix([[ 2,  3],
        [ 6, 11]])

In [13]:
matriz ** 2

matrix([[ 74,  84,  94, 100],
        [170, 196, 222, 240],
        [266, 308, 350, 380],
        [257, 298, 339, 369]])

In [48]:
result = rbf_kernel(matriz, gamma=0.001)
result

array([[1.        , 0.938005  , 0.77414197, 0.78584163],
       [0.938005  , 1.        , 0.938005  , 0.94459407],
       [0.77414197, 0.938005  , 1.        , 0.9990005 ],
       [0.78584163, 0.94459407, 0.9990005 , 1.        ]])

In [49]:
# Tamanho da matriz:
mem_size = result.nbytes
mem_size

128

### Tentando implementar o rbf kernel na mão...


In [36]:
def rbf_kernel(X, Y=None, gamma=None):
    """
    Compute the rbf (gaussian) kernel between X and Y::

        K(x, y) = exp(-gamma ||x-y||^2)

    for each pair of rows x in X and y in Y.

    Read more in the :ref:`User Guide <rbf_kernel>`.

    Parameters
    ----------
    X : array of shape (n_samples_X, n_features)

    Y : array of shape (n_samples_Y, n_features)

    gamma : float, default None
        If None, defaults to 1.0 / n_features

    Returns
    -------
    kernel_matrix : array of shape (n_samples_X, n_samples_Y)
    """
    X, Y = check_pairwise_arrays(X, Y)
    if gamma is None:
        gamma = 1.0 / X.shape[1]

    K = euclidean_distances(X, Y, squared=True)
    K *= -gamma
    np.exp(K, K)  # exponentiate K in-place
    return K
