# Transfer learning feature compactation
The objetive is understand how an mfcc is compacted to a feature vector

In [ ]:
# It means it will be 20 mfccs, in the example below it is over 97 frames
mfcc = librosa.feature.mfcc(src, SR, n_mfcc=20) # shape = (20, 97) 

dmfcc = mfcc[:, 1:] - mfcc[:, :-1]
ddmfcc = dmfcc[:, 1:] - dmfcc[:, :-1]
return np.concatenate(
                        (np.mean(mfcc, axis=1  ), # to take the mean of each row
                         np.std(mfcc, axis=1   ), # to take the std deviation of each row
                         np.mean(dmfcc, axis=1 ), # to take the std mean of the dmfcc on each row
                         np.std(dmfcc, axis=1  ),
                         np.mean(ddmfcc, axis=1), 
                         np.std(ddmfcc, axis=1))
                          , axis=0
                        )
                    )


In [2]:
import librosa
import librosa.display
import numpy as np

In [3]:
x, fs = librosa.load('audio_simple_loop.wav')
librosa.display.waveplot(x, sr=fs)

In [5]:
mfcc = librosa.feature.mfcc(x, sr=fs)
print(mfcc.shape)

(20, 97)


In [6]:
def mfcc_to_feature(mfcc):
    dmfcc = mfcc[:, 1:] - mfcc[:, :-1] # ignore the first mfcc that does not convey info
    ddmfcc = dmfcc[:, 1:] - dmfcc[:, :-1]
    return np.concatenate((np.mean(mfcc, axis=1), np.std(mfcc, axis=1),
                           np.mean(dmfcc, axis=1), np.std(dmfcc, axis=1),
                           np.mean(ddmfcc, axis=1), np.std(ddmfcc, axis=1))
                          , axis=0)

In [7]:
res = mfcc_to_feature(mfcc)
res.shape

(120,)

In [17]:
# I wanna understand how this matrix operation works
mat_example = [[1,2,3],
               [4,5,6],
               [7,8,9]]

mat_example = np.matrix(mat_example)
print(mat_example)

slice_mat1 = mat_example[:, 1:]
print(slice_mat1)

slice_mat2 = mat_example[:, :-1]
print(slice_mat2)

dmat_example = mat_example[:, 1:] - mat_example[:, :-1]
dmat_example

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[1 2]
 [4 5]
 [7 8]]


matrix([[1, 1],
        [1, 1],
        [1, 1]])